apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclaw.fullname" . }}-init-scripts
  namespace: {{ .Release.Namespace }}
data:
  init-script.sh: |
{{ .Files.Get "files/init-script.sh" | indent 4 }}
