apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.fullname" . }}-external-kubeconfig
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  kubeconfig: |
{{ .Files.Get "files/target-kubeconfig.yaml" | indent 4 }}
